---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-demo-restore-mrzegwyz
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
