---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aadenv-100002

resources:
  - namespace.yaml
  - base

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      managed-by: aad

images:
  - name: portal
    newName: ghcr.io/stefanprodan/podinfo
    newTag: 6.7.1
  - name: redis
    newName: redis
    newTag: 7-alpine

replicas:
  - name: portal
    count: 1
  - name: redis
    count: 1
