---
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app.kubernetes.io/name: portal
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: portal-banco-dev2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: portal
