---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-restore-demo-mrww5qzy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: env-restore-demo-mrww5qzy
    spec:
      initContainers:
        - name: aad-init
          image: postgres:placeholder
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "#!/bin/bash\necho \"No init script configured for postgres\""
      containers:
        - name: postgres
          image: postgres:placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
