---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aadenv-80003

resources:
  - namespace.yaml
  - base

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      managed-by: aad

images:
  - name: adminer
    newName: adminer
    newTag: latest
  - name: kafka
    newName: apache/kafka
    newTag: latest
  - name: kafka-ui
    newName: kafbat/kafka-ui
    newTag: latest
  - name: postgres
    newName: postgres
    newTag: latest

replicas:
  - name: adminer
    count: 1
  - name: kafka
    count: 1
  - name: kafka-ui
    count: 1
  - name: postgres
    count: 1
