---
apiVersion: v1
kind: Service
metadata:
  name: flavio-web-test
  labels:
    app.kubernetes.io/name: flavio-web-test
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-flavio-web-test-mqzpo1de
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: flavio-web-test
