---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/managed-by: aad
    app.kubernetes.io/part-of: vso3-0325
spec:
  type: kv-v2
  mount: aad
  path: environments/aad-env-40062/db
  vaultAuthRef: aad-vault-auth
  refreshAfter: 1h
  destination:
    name: db-secrets
    create: true
    type: Opaque
