---
apiVersion: v1
kind: Service
metadata:
  name: flavio-web
  labels:
    app.kubernetes.io/name: flavio-web
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-flavio2-mqzoydga
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: flavio-web
