---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aad-gitopsenv-20020

resources:
  - namespace.yaml
  - base

labels:
  - includeSelectors: false
    pairs:
      environment: "dev"
      managed-by: "aad"

images:
  - name: flavio-web
    newName: nginx
    newTag: 1-alpine

replicas:
  - name: flavio-web
    count: 1
