---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/managed-by: aad
    app.kubernetes.io/part-of: vsoab-3527
spec:
  type: kv-v2
  mount: secret
  path: aad/environments/40064/secrets/db
  vaultAuthRef: aad-vault-auth
  refreshAfter: 1h
  destination:
    name: db-secrets
    create: true
    type: Opaque
