---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aad-env-40064-vault
  labels:
    app.kubernetes.io/managed-by: aad
    app.kubernetes.io/part-of: vsoab-3527
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: aad-vault-auth
  labels:
    app.kubernetes.io/managed-by: aad
    app.kubernetes.io/part-of: vsoab-3527
spec:
  vaultConnectionRef: "vault/vault-connection"
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: "aad-env"
    serviceAccount: aad-env-40064-vault
    audiences:
      - vault
    tokenExpirationSeconds: 600
