---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-portal---banco--wizard--mqv3suir
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
