---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: vso2-9519
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: vso2-9519
    spec:
      containers:
        - name: db
          image: db:placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
