---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aad-env-3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/echoesdigital/aad-gitops-sim.git
    targetRevision: main
    path: environments/aad-env-3
  destination:
    server: https://kubernetes.default.svc
    namespace: aadaad-env-3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
