---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aad-env-40051
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.aad: ""
    notifications.argoproj.io/subscribe.on-health-degraded.aad: ""
    notifications.argoproj.io/subscribe.on-sync-failed.aad: ""
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/echoesdigital/aad-gitops-sim
    targetRevision: main
    path: environments/aad-env-40051
  destination:
    server: https://kubernetes.default.svc
    namespace: aad-gitopsenv-40051
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
