---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-portal---banco--wizard--mqv6iqj6
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: env-portal---banco--wizard--mqv6iqj6
    spec:
      containers:
        - name: redis
          image: redis:placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6379
          env:
            - name: CONNECTION_STRING
              value: "$HOST_INTERNO:$PORTA_INTERNA"
            - name: HOST_INTERNO
              value: ""
            - name: PORTA_INTERNA
              value: "6379"
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
