---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aad-gitopsenv-20031

resources:
  - namespace.yaml
  - base

labels:
  - includeSelectors: false
    pairs:
      environment: "dev"
      managed-by: "aad"

images:
  - name: web
    newName: nginx
    newTag: "1"

replicas:
  - name: web
    count: 1
