---
apiVersion: v1
kind: Service
metadata:
  name: web-demo
  labels:
    app.kubernetes.io/name: web-demo
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-web-demo-mrtk91jb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: web-demo
