---
apiVersion: v1
kind: Service
metadata:
  name: foo-web
  labels:
    app.kubernetes.io/name: foo-web
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-foo-web-mqzzyzba
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: foo-web
