---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: env-postgres---kafka-mr0pcu1s
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: kafka-ui
