---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/managed-by: aad
    app.kubernetes.io/part-of: env-demo-restore-mrzegwyz
spec:
  type: kv-v2
  mount: secret
  path: aad/environments/40066/secrets/postgres
  vaultAuthRef: aad-vault-auth
  refreshAfter: 1h
  destination:
    name: postgres-secrets
    create: true
    type: Opaque
